## Import the library

In [1]:
import numpy as np

## Array creation

### 1D arrays

In [2]:
arr = np.array([1, 2, 3])
print(arr)

arr = np.zeros(4)
print(arr)

arr = np.arange(1, 4, 2)
print(arr)

arr = np.random.rand(2)
print(arr)

arr = np.empty(3)
print(arr)

[1 2 3]
[0. 0. 0. 0.]
[1 3]
[0.52748036 0.49106974]
[4.9e-324 9.9e-324 1.5e-323]


### 2D arrays

In [3]:
arr = np.array([[1, 2, 3], [1, 2, 3]], dtype=float)
print(arr)

arr = np.zeros((2, 4))
print(arr)

arr = np.full((1, 4), 2.0)
print(arr)

[[1. 2. 3.]
 [1. 2. 3.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[2. 2. 2. 2.]]


## Array attributes

In [4]:
arr = np.array([[1, 2, 3], [1, 2, 3]], dtype=float)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.shape)
print(arr.itemsize)

2
6
float64
(2, 3)
8


## Indexing & slicing

### 1D indexing

In [5]:
arr = np.array([1.0, 2.0, 3.0, 4.0])
print(arr[0])

arr[1] = 3.0
print(arr)

print(arr[-4])

arr[-3] = 2.0
print(arr)

1.0
[1. 3. 3. 4.]
1.0
[1. 2. 3. 4.]


### 2D indexing

In [6]:
arr = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0],
])
print(arr[0][3])
print(arr[-2][3])

arr[1] = 3.0
print(arr)

arr[0][-3] = 3.0
print(arr)

4.0
4.0
[[1. 2. 3. 4.]
 [3. 3. 3. 3.]]
[[1. 3. 3. 4.]
 [3. 3. 3. 3.]]


### Slicing

In [7]:
arr = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0],
])
print(arr[0])
print(arr[0][0::2])
print(arr[0:2, 1:3])
print(arr[0:2, -4::2])

[1. 2. 3. 4.]
[1. 3.]
[[2. 3.]
 [6. 7.]]
[[1. 3.]
 [5. 7.]]


## Reshape

In [8]:
arr = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
])
print(arr.shape)

arr = np.reshape(arr, (3, 2))
print(arr)
print(arr.shape)

(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
(3, 2)


In [ ]:
# arr = np.reshape(arr, (3, 3))  # ValueError: cannot reshape 6 elements into (3, 3)

## Arithmetic operations

In [9]:
arr1 = np.array([1.0, 2.0, 3.0, 4.0])
arr2 = np.array([5.0, 6.0, 7.0, 8.0])

print(arr1 + arr2)
print(np.add(arr1, arr2))

print(arr1 % arr2)
print(np.mod(arr1, arr2))

[ 6.  8. 10. 12.]
[ 6.  8. 10. 12.]
[1. 2. 3. 4.]
[1. 2. 3. 4.]


## Comparison operations

In [10]:
arr1 = np.array([1.0, 2.0, 3.0, 4.0])
arr2 = np.array([5.0, 2.0, 7.0, 8.0])

print(arr1 < arr2)
print(np.less(arr1, arr2))

print(arr1 != arr2)
print(np.not_equal(arr1, arr2))

print(np.logical_or(np.less(arr1, arr2), np.not_equal(arr1, arr2)))

[ True False  True  True]
[ True False  True  True]
[ True False  True  True]
[ True False  True  True]
[ True False  True  True]


## Math & rounding functions

In [11]:
arr = np.random.rand(2, 3)
print(arr)
print(np.sin(arr))
print(np.round(arr))
print(np.floor(arr))
print(np.ceil(arr))

[[0.44226772 0.89594226 0.35349171]
 [0.7089901  0.32634174 0.513741  ]]
[[0.4279901  0.78079813 0.34617573]
 [0.65106757 0.32058    0.49143876]]
[[0. 1. 0.]
 [1. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


## Aggregation

In [12]:
arr = np.array([1.0, 2.0, 3.0, 4.0])
print(np.max(arr))

arr = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0],
])
print(np.max(arr))
print(np.max(arr, axis=0))
print(np.max(arr, axis=1))

4.0
8.0
[5. 6. 7. 8.]
[4. 8.]


## String operations

In [19]:
str_arr1 = np.array(["Iphone: ", "Price: "])
str_arr2 = np.array(["17", "$900"])

print(np.char.add(str_arr1, str_arr2))
print(np.char.multiply(str_arr1, 3))
print(np.char.upper(str_arr1))
print(np.char.equal(str_arr1, str_arr2))

['Iphone: 17' 'Price: $900']
['Iphone: Iphone: Iphone: ' 'Price: Price: Price: ']
['IPHONE: ' 'PRICE: ']
[False False]


## Broadcasting

In [14]:
arr1 = np.array([1.0, 2.0, 3.0, 4.0])
arr2 = np.array([[1.0], [5.0]])

print(np.add(arr1, 3.0))
print(np.add(arr1, arr2))

[4. 5. 6. 7.]
[[2. 3. 4. 5.]
 [6. 7. 8. 9.]]


## Dot product

In [15]:
print(np.dot(np.array([1.0, 2.0, 3.0]), 2))

arr1 = np.array([1.0, 2.0, 3.0])
arr2 = np.array([1.0, 2.0, 1.0])
print(np.dot(arr1, arr2))

arr1 = np.array([[3.0, 4.0, 1.0], [4.0, 3.0, 2.0]])
arr2 = np.array([[1.0, 2.0], [0.0, 1.0], [2.0, 0.0]])
print(np.dot(arr1, arr2))

[2. 4. 6.]
8.0
[[ 5. 10.]
 [ 8. 11.]]


## Transpose & flatten

In [16]:
arr = np.array([[1, 2, 3], [3, 4, 5]])

print(np.transpose(arr))
print(np.transpose(arr).shape)

print(arr.flatten())
print(arr.flatten().shape)

[[1 3]
 [2 4]
 [3 5]]
(3, 2)
[1 2 3 3 4 5]
(6,)
